
namespace System
{
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// Html定义的语言代码 http://www.w3schools.com/cn/tags/ref_language_codes.asp
    /// 语言代码: http://www.lingoes.cn/zh/translator/langcode.htm
    /// </remarks>
    public enum LangEnum
    {
        ///<summary>
        ///英语
        ///</summary>
        En = 1,
        ///<summary>
        ///中文
        ///</summary>
        Zh = 2,
    }

    public enum LangAllEnum
    {
        ///<summary>
        ///英语
        ///</summary>
        En = 1,
        ///<summary>
        ///中文
        ///</summary>
        Zh = 2,
        ///<summary>
        ///南非语
        ///</summary>
        Af,
        ///<summary>
        ///南非语
        ///</summary>
        Afza,
        ///<summary>
        ///阿拉伯语
        ///</summary>
        Ar,
        ///<summary>
        ///阿拉伯语(阿联酋)
        ///</summary>
        Arae,
        ///<summary>
        ///阿拉伯语(巴林)
        ///</summary>
        Arbh,
        ///<summary>
        ///阿拉伯语(阿尔及利亚)
        ///</summary>
        Ardz,
        ///<summary>
        ///阿拉伯语(埃及)
        ///</summary>
        Areg,
        ///<summary>
        ///阿拉伯语(伊拉克)
        ///</summary>
        Ariq,
        ///<summary>
        ///阿拉伯语(约旦)
        ///</summary>
        Arjo,
        ///<summary>
        ///阿拉伯语(科威特)
        ///</summary>
        Arkw,
        ///<summary>
        ///阿拉伯语(黎巴嫩)
        ///</summary>
        Arlb,
        ///<summary>
        ///阿拉伯语(利比亚)
        ///</summary>
        Arly,
        ///<summary>
        ///阿拉伯语(摩洛哥)
        ///</summary>
        Arma,
        ///<summary>
        ///阿拉伯语(阿曼)
        ///</summary>
        Arom,
        ///<summary>
        ///阿拉伯语(卡塔尔)
        ///</summary>
        Arqa,
        ///<summary>
        ///阿拉伯语(沙特阿拉伯)
        ///</summary>
        Arsa,
        ///<summary>
        ///阿拉伯语(叙利亚)
        ///</summary>
        Arsy,
        ///<summary>
        ///阿拉伯语(突尼斯)
        ///</summary>
        Artn,
        ///<summary>
        ///阿拉伯语(也门)
        ///</summary>
        Arye,
        ///<summary>
        ///阿塞拜疆语
        ///</summary>
        Az,
        ///<summary>
        ///阿塞拜疆语(拉丁文)阿塞拜疆语(西里尔文)
        ///</summary>
        Azaz,

        ///<summary>
        ///比利时语
        ///</summary>
        Be,
        ///<summary>
        ///比利时语
        ///</summary>
        Beby,
        ///<summary>
        ///保加利亚语
        ///</summary>
        Bg,
        ///<summary>
        ///保加利亚语
        ///</summary>
        Bgbg,
        ///<summary>
        ///波斯尼亚语(拉丁文，波斯尼亚和黑塞哥维那)
        ///</summary>
        Bsba,
        ///<summary>
        ///加泰隆语
        ///</summary>
        Ca,
        ///<summary>
        ///加泰隆语
        ///</summary>
        Caes,
        ///<summary>
        ///捷克语
        ///</summary>
        Cs,
        ///<summary>
        ///捷克语
        ///</summary>
        Cscz,
        ///<summary>
        ///威尔士语
        ///</summary>
        Cy,
        ///<summary>
        ///威尔士语
        ///</summary>
        Cygb,
        ///<summary>
        ///丹麦语
        ///</summary>
        Da,
        ///<summary>
        ///丹麦语
        ///</summary>
        Dadk,
        ///<summary>
        ///德语
        ///</summary>
        De,
        ///<summary>
        ///德语(奥地利)
        ///</summary>
        Deat,
        ///<summary>
        ///德语(瑞士)
        ///</summary>
        Dech,
        ///<summary>
        ///德语(德国)
        ///</summary>
        Dede,
        ///<summary>
        ///德语(列支敦士登)
        ///</summary>
        Deli,
        ///<summary>
        ///德语(卢森堡)
        ///</summary>
        Delu,
        ///<summary>
        ///第维埃语
        ///</summary>
        Dv,
        ///<summary>
        ///第维埃语
        ///</summary>
        Dvmv,
        ///<summary>
        ///希腊语
        ///</summary>
        El,
        ///<summary>
        ///希腊语
        ///</summary>
        Elgr,
        ///<summary>
        ///英语(澳大利亚)
        ///</summary>
        Enau,
        ///<summary>
        ///英语(伯利兹)
        ///</summary>
        Enbz,
        ///<summary>
        ///英语(加拿大)
        ///</summary>
        Enca,
        ///<summary>
        ///英语(加勒比海)
        ///</summary>
        Encb,
        ///<summary>
        ///英语(英国)
        ///</summary>
        Engb,
        ///<summary>
        ///英语(爱尔兰)
        ///</summary>
        Enie,
        ///<summary>
        ///英语(牙买加)
        ///</summary>
        Enjm,
        ///<summary>
        ///英语(新西兰)
        ///</summary>
        Ennz,
        ///<summary>
        ///英语(菲律宾)
        ///</summary>
        Enph,
        ///<summary>
        ///英语(特立尼达)
        ///</summary>
        Entt,
        ///<summary>
        ///英语(美国)
        ///</summary>
        Enus,
        ///<summary>
        ///英语(南非)
        ///</summary>
        Enza,
        ///<summary>
        ///英语(津巴布韦)
        ///</summary>
        Enzw,
        ///<summary>
        ///世界语
        ///</summary>
        Eo,
        ///<summary>
        ///西班牙语
        ///</summary>
        Es,
        ///<summary>
        ///西班牙语(阿根廷)
        ///</summary>
        Esar,
        ///<summary>
        ///西班牙语(玻利维亚)
        ///</summary>
        Esbo,
        ///<summary>
        ///西班牙语(智利)
        ///</summary>
        Escl,
        ///<summary>
        ///西班牙语(哥伦比亚)
        ///</summary>
        Esco,
        ///<summary>
        ///西班牙语(哥斯达黎加)
        ///</summary>
        Escr,
        ///<summary>
        ///西班牙语(多米尼加共和国)
        ///</summary>
        Esdo,
        ///<summary>
        ///西班牙语(厄瓜多尔)
        ///</summary>
        Esec,
        ///<summary>
        ///西班牙语(传统)西班牙语(国际)
        ///</summary>
        Eses,

        ///<summary>
        ///西班牙语(危地马拉)
        ///</summary>
        Esgt,
        ///<summary>
        ///西班牙语(洪都拉斯)
        ///</summary>
        Eshn,
        ///<summary>
        ///西班牙语(墨西哥)
        ///</summary>
        Esmx,
        ///<summary>
        ///西班牙语(尼加拉瓜)
        ///</summary>
        Esni,
        ///<summary>
        ///西班牙语(巴拿马)
        ///</summary>
        Espa,
        ///<summary>
        ///西班牙语(秘鲁)
        ///</summary>
        Espe,
        ///<summary>
        ///西班牙语(波多黎各(美))
        ///</summary>
        Espr,
        ///<summary>
        ///西班牙语(巴拉圭)
        ///</summary>
        Espy,
        ///<summary>
        ///西班牙语(萨尔瓦多)
        ///</summary>
        Essv,
        ///<summary>
        ///西班牙语(乌拉圭)
        ///</summary>
        Esuy,
        ///<summary>
        ///西班牙语(委内瑞拉)
        ///</summary>
        Esve,
        ///<summary>
        ///爱沙尼亚语
        ///</summary>
        Et,
        ///<summary>
        ///爱沙尼亚语
        ///</summary>
        Etee,
        ///<summary>
        ///巴士克语
        ///</summary>
        Eu,
        ///<summary>
        ///巴士克语
        ///</summary>
        Eues,
        ///<summary>
        ///法斯语
        ///</summary>
        Fa,
        ///<summary>
        ///法斯语
        ///</summary>
        Fair,
        ///<summary>
        ///芬兰语
        ///</summary>
        Fi,
        ///<summary>
        ///芬兰语
        ///</summary>
        Fifi,
        ///<summary>
        ///法罗语
        ///</summary>
        Fo,
        ///<summary>
        ///法罗语
        ///</summary>
        Fofo,
        ///<summary>
        ///法语
        ///</summary>
        Fr,
        ///<summary>
        ///法语(比利时)
        ///</summary>
        Frbe,
        ///<summary>
        ///法语(加拿大)
        ///</summary>
        Frca,
        ///<summary>
        ///法语(瑞士)
        ///</summary>
        Frch,
        ///<summary>
        ///法语(法国)
        ///</summary>
        Frfr,
        ///<summary>
        ///法语(卢森堡)
        ///</summary>
        Frlu,
        ///<summary>
        ///法语(摩纳哥)
        ///</summary>
        Frmc,
        ///<summary>
        ///加里西亚语
        ///</summary>
        Gl,
        ///<summary>
        ///加里西亚语
        ///</summary>
        Gles,
        ///<summary>
        ///古吉拉特语
        ///</summary>
        Gu,
        ///<summary>
        ///古吉拉特语
        ///</summary>
        Guin,
        ///<summary>
        ///希伯来语
        ///</summary>
        He,
        ///<summary>
        ///希伯来语
        ///</summary>
        Heil,
        ///<summary>
        ///印地语
        ///</summary>
        Hi,
        ///<summary>
        ///印地语
        ///</summary>
        Hiin,
        ///<summary>
        ///克罗地亚语
        ///</summary>
        Hr,
        ///<summary>
        ///克罗地亚语(波斯尼亚和黑塞哥维那)
        ///</summary>
        Hrba,
        ///<summary>
        ///克罗地亚语
        ///</summary>
        Hrhr,
        ///<summary>
        ///匈牙利语
        ///</summary>
        Hu,
        ///<summary>
        ///匈牙利语
        ///</summary>
        Huhu,
        ///<summary>
        ///亚美尼亚语
        ///</summary>
        Hy,
        ///<summary>
        ///亚美尼亚语
        ///</summary>
        Hyam,
        ///<summary>
        ///印度尼西亚语
        ///</summary>
        Id,
        ///<summary>
        ///印度尼西亚语
        ///</summary>
        Idid,
        ///<summary>
        ///冰岛语
        ///</summary>
        Is,
        ///<summary>
        ///冰岛语
        ///</summary>
        Isis,
        ///<summary>
        ///意大利语
        ///</summary>
        It,
        ///<summary>
        ///意大利语(瑞士)
        ///</summary>
        Itch,
        ///<summary>
        ///意大利语(意大利)
        ///</summary>
        Itit,
        ///<summary>
        ///日语
        ///</summary>
        Ja,
        ///<summary>
        ///日语
        ///</summary>
        Jajp,
        ///<summary>
        ///格鲁吉亚语
        ///</summary>
        Ka,
        ///<summary>
        ///格鲁吉亚语
        ///</summary>
        Kage,
        ///<summary>
        ///哈萨克语
        ///</summary>
        Kk,
        ///<summary>
        ///哈萨克语
        ///</summary>
        Kkkz,
        ///<summary>
        ///卡纳拉语
        ///</summary>
        Kn,
        ///<summary>
        ///卡纳拉语
        ///</summary>
        Knin,
        ///<summary>
        ///朝鲜语
        ///</summary>
        Ko,
        ///<summary>
        ///朝鲜语
        ///</summary>
        Kokr,
        ///<summary>
        ///孔卡尼语
        ///</summary>
        Kok,
        ///<summary>
        ///孔卡尼语
        ///</summary>
        Kokin,
        ///<summary>
        ///吉尔吉斯语
        ///</summary>
        Ky,
        ///<summary>
        ///吉尔吉斯语(西里尔文)
        ///</summary>
        Kykg,
        ///<summary>
        ///立陶宛语
        ///</summary>
        Lt,
        ///<summary>
        ///立陶宛语
        ///</summary>
        Ltlt,
        ///<summary>
        ///拉脱维亚语
        ///</summary>
        Lv,
        ///<summary>
        ///拉脱维亚语
        ///</summary>
        Lvlv,
        ///<summary>
        ///毛利语
        ///</summary>
        Mi,
        ///<summary>
        ///毛利语
        ///</summary>
        Minz,
        ///<summary>
        ///马其顿语
        ///</summary>
        Mk,
        ///<summary>
        ///马其顿语(fyrom)
        ///</summary>
        Mkmk,
        ///<summary>
        ///蒙古语
        ///</summary>
        Mn,
        ///<summary>
        ///蒙古语(西里尔文)
        ///</summary>
        Mnmn,
        ///<summary>
        ///马拉地语
        ///</summary>
        Mr,
        ///<summary>
        ///马拉地语
        ///</summary>
        Mrin,
        ///<summary>
        ///马来语
        ///</summary>
        Ms,
        ///<summary>
        ///马来语(文莱达鲁萨兰)
        ///</summary>
        Msbn,
        ///<summary>
        ///马来语(马来西亚)
        ///</summary>
        Msmy,
        ///<summary>
        ///马耳他语
        ///</summary>
        Mt,
        ///<summary>
        ///马耳他语
        ///</summary>
        Mtmt,
        ///<summary>
        ///挪威语(伯克梅尔)
        ///</summary>
        Nb,
        ///<summary>
        ///挪威语(伯克梅尔)(挪威)
        ///</summary>
        Nbno,
        ///<summary>
        ///荷兰语
        ///</summary>
        Nl,
        ///<summary>
        ///荷兰语(比利时)
        ///</summary>
        Nlbe,
        ///<summary>
        ///荷兰语(荷兰)
        ///</summary>
        Nlnl,
        ///<summary>
        ///挪威语(尼诺斯克)(挪威)
        ///</summary>
        Nnno,
        ///<summary>
        ///北梭托语
        ///</summary>
        Ns,
        ///<summary>
        ///北梭托语
        ///</summary>
        Nsza,
        ///<summary>
        ///旁遮普语
        ///</summary>
        Pa,
        ///<summary>
        ///旁遮普语
        ///</summary>
        Pain,
        ///<summary>
        ///波兰语
        ///</summary>
        Pl,
        ///<summary>
        ///波兰语
        ///</summary>
        Plpl,
        ///<summary>
        ///葡萄牙语
        ///</summary>
        Pt,
        ///<summary>
        ///葡萄牙语(巴西)
        ///</summary>
        Ptbr,
        ///<summary>
        ///葡萄牙语(葡萄牙)
        ///</summary>
        Ptpt,
        ///<summary>
        ///克丘亚语
        ///</summary>
        Qu,
        ///<summary>
        ///克丘亚语(玻利维亚)
        ///</summary>
        Qubo,
        ///<summary>
        ///克丘亚语(厄瓜多尔)
        ///</summary>
        Quec,
        ///<summary>
        ///克丘亚语(秘鲁)
        ///</summary>
        Qupe,
        ///<summary>
        ///罗马尼亚语
        ///</summary>
        Ro,
        ///<summary>
        ///罗马尼亚语
        ///</summary>
        Roro,
        ///<summary>
        ///俄语
        ///</summary>
        Ru,
        ///<summary>
        ///俄语
        ///</summary>
        Ruru,
        ///<summary>
        ///梵文
        ///</summary>
        Sa,
        ///<summary>
        ///梵文
        ///</summary>
        Sain,
        ///<summary>
        ///北萨摩斯语
        ///</summary>
        Se,
        ///<summary>
        ///北萨摩斯语(芬兰) 斯科特萨摩斯语(芬兰) 伊那里萨摩斯语(芬兰)
        ///</summary>
        Sefi,


        ///<summary>
        ///北萨摩斯语(挪威)律勒欧萨摩斯语(挪威) 南萨摩斯语(挪威)
        ///</summary>
        Seno,


        ///<summary>
        ///北萨摩斯语(瑞典) 律勒欧萨摩斯语(瑞典) 南萨摩斯语(瑞典)
        ///</summary>
        Sese,


        ///<summary>
        ///斯洛伐克语
        ///</summary>
        Sk,
        ///<summary>
        ///斯洛伐克语
        ///</summary>
        Sksk,
        ///<summary>
        ///斯洛文尼亚语
        ///</summary>
        Sl,
        ///<summary>
        ///斯洛文尼亚语
        ///</summary>
        Slsi,
        ///<summary>
        ///阿尔巴尼亚语
        ///</summary>
        Sq,
        ///<summary>
        ///阿尔巴尼亚语
        ///</summary>
        Sqal,
        ///<summary>
        ///塞尔维亚语(拉丁文，波斯尼亚和黑塞哥维那) 塞尔维亚语(西里尔文，波斯尼亚和黑塞哥维那)
        ///</summary>
        Srba,

        ///<summary>
        ///塞尔维亚(拉丁) 塞尔维亚(西里尔文)
        ///</summary>
        Srsp,

        ///<summary>
        ///瑞典语
        ///</summary>
        Sv,
        ///<summary>
        ///瑞典语(芬兰)
        ///</summary>
        Svfi,
        ///<summary>
        ///瑞典语
        ///</summary>
        Svse,
        ///<summary>
        ///斯瓦希里语
        ///</summary>
        Sw,
        ///<summary>
        ///斯瓦希里语
        ///</summary>
        Swke,
        ///<summary>
        ///叙利亚语
        ///</summary>
        Syr,
        ///<summary>
        ///叙利亚语
        ///</summary>
        Syrsy,
        ///<summary>
        ///泰米尔语
        ///</summary>
        Ta,
        ///<summary>
        ///泰米尔语
        ///</summary>
        Tain,
        ///<summary>
        ///泰卢固语
        ///</summary>
        Te,
        ///<summary>
        ///泰卢固语
        ///</summary>
        Tein,
        ///<summary>
        ///泰语
        ///</summary>
        Th,
        ///<summary>
        ///泰语
        ///</summary>
        Thth,
        ///<summary>
        ///塔加路语
        ///</summary>
        Tl,
        ///<summary>
        ///塔加路语(菲律宾)
        ///</summary>
        Tlph,
        ///<summary>
        ///茨瓦纳语
        ///</summary>
        Tn,
        ///<summary>
        ///茨瓦纳语
        ///</summary>
        Tnza,
        ///<summary>
        ///土耳其语
        ///</summary>
        Tr,
        ///<summary>
        ///土耳其语
        ///</summary>
        Trtr,
        ///<summary>
        ///宗加语
        ///</summary>
        Ts,
        ///<summary>
        ///鞑靼语
        ///</summary>
        Tt,
        ///<summary>
        ///鞑靼语
        ///</summary>
        Ttru,
        ///<summary>
        ///乌克兰语
        ///</summary>
        Uk,
        ///<summary>
        ///乌克兰语
        ///</summary>
        Ukua,
        ///<summary>
        ///乌都语
        ///</summary>
        Ur,
        ///<summary>
        ///乌都语
        ///</summary>
        Urpk,
        ///<summary>
        ///乌兹别克语
        ///</summary>
        Uz,
        ///<summary>
        ///乌兹别克语(拉丁文)乌兹别克语(西里尔文)
        ///</summary>
        Uzuz,

        ///<summary>
        ///越南语
        ///</summary>
        Vi,
        ///<summary>
        ///越南语
        ///</summary>
        Vivn,
        ///<summary>
        ///班图语
        ///</summary>
        Xh,
        ///<summary>
        ///班图语
        ///</summary>
        Xhza,
        ///<summary>
        ///中文(简体)
        ///</summary>
        Zhcn,
        ///<summary>
        ///中文(香港)
        ///</summary>
        Zhhk,
        ///<summary>
        ///中文(澳门)
        ///</summary>
        Zhmo,
        ///<summary>
        ///中文(新加坡)
        ///</summary>
        Zhsg,
        ///<summary>
        ///中文(繁体)
        ///</summary>
        Zhtw,
        ///<summary>
        ///祖鲁语
        ///</summary>
        Zu,
        ///<summary>
        ///祖鲁语
        ///</summary>
        Zuza,
    }
}

